In [1]:
import pandas as pd
from tqdm import tqdm
import numpy as np
import itertools

In [2]:
# Carregar o conjunto de dados
print("Carregando o conjunto de dados...")
df = pd.read_csv('D:/projetos/simpress/testes/arquivo_final-29-05-2024.csv')
df = df[df['BrandName'] == 'HP']
df = df.sort_values(by=['RealDateCapture','SerialNumber'], ascending=[False,True])

Carregando o conjunto de dados...

In [3]:
# Converte a coluna 'RealDateCapture' do df para datetime
df['RealDateCapture'] = pd.to_datetime(df['RealDateCapture'], format='%d-%m-%Y')

In [4]:
# Salva o arquivo csv com os dados originais
df.to_csv('df_original.csv')

In [5]:
print(f"Conjunto de dados carregado com {len(df)} registros.")

Conjunto de dados carregado com 282351 registros.

In [6]:
# Selecionar impressoras únicas (linhas únicas com base na coluna 'SerialNumber')
imp = df.drop_duplicates(subset='SerialNumber')

In [7]:
print(f'Foram encontradas {len(imp)} impressoras')

Foram encontradas 348 impressoras

In [8]:
# Seleciona as colunas do DataFrame 'imp'
imp = imp[['EnterpriseName', 'PrinterDeviceID', 'BrandName', 'PrinterModelName', 'SerialNumber']]

In [9]:
# Gera arquivo csv com as impressoras do dataframe
imp.to_csv('data/df_impressoras.csv')

In [10]:
# Gera um DataFrame com datas
date_range = pd.date_range(start='01-01-2022', end='28-05-2024', freq='D')
df_dates = pd.DataFrame({'RealDateCapture': date_range})

In [11]:
# Adicionar a coluna 'key' para combinação
imp['key'] = 1
df_dates['key'] = 1

# Combinação dos DataFrames
df_full_datas = pd.merge(imp, df_dates, on='key').drop('key', axis=1)

In [12]:
df_full_datas

,EnterpriseName,PrinterDeviceID,BrandName,PrinterModelName,SerialNumber,RealDateCapture
0,9853_TRE_BA,280,HP,LaserJet MFP E52645,BRBSN8FC4P,2022-01-01
1,9853_TRE_BA,280,HP,LaserJet MFP E52645,BRBSN8FC4P,2022-01-02
2,9853_TRE_BA,280,HP,LaserJet MFP E52645,BRBSN8FC4P,2022-01-03
3,9853_TRE_BA,280,HP,LaserJet MFP E52645,BRBSN8FC4P,2022-01-04
4,9853_TRE_BA,280,HP,LaserJet MFP E52645,BRBSN8FC4P,2022-01-05
...,...,...,...,...,...,...
305887,9853_TRE_BA,659,HP,Laser 408dn,BRBSRC60PQ,2024-05-24
305888,9853_TRE_BA,659,HP,Laser 408dn,BRBSRC60PQ,2024-05-25
305889,9853_TRE_BA,659,HP,Laser 408dn,BRBSRC60PQ,2024-05-26
305890,9853_TRE_BA,659,HP,Laser 408dn,BRBSRC60PQ,2024-05-27
305891,9853_TRE_BA,659,HP,Laser 408dn,BRBSRC60PQ,2024-05-28

In [13]:
# Gera um arquivo csv com as datas mescladas com os dados
df_full_datas.to_csv("df_full_datas.csv")

In [14]:
# Faz o merge com o DataFrame original
df_merged = df_full_datas.merge(df, how='left', on=['RealDateCapture','SerialNumber','EnterpriseName','PrinterDeviceID','BrandName','PrinterModelName'])

In [15]:
# Preenche os valores ausentes com nan
df_merged.fillna(value=np.nan, inplace=True)

In [16]:
# ordena os registros pelas colunas 'RealDateCapture' e 'SerialNumber'
df_merged = df_merged.sort_values(by=['RealDateCapture','SerialNumber'], ascending=False)

In [17]:
# Gera um arquivo csv com os dados mescladas
df_merged.to_csv('df_merged.csv')

In [18]:
df_merged

,EnterpriseName,PrinterDeviceID,BrandName,PrinterModelName,SerialNumber,RealDateCapture,AddressName,DateTimeRead,ReferenceMono,ReferenceColor,Engaged
283916,9853_TRE_BA,370,HP,Color LaserJet MFP E77830,CND1N49018,2024-05-28,10.5.201.248 (Network),2024-05-28T22:39:24,5575.0,25350.0,False
283037,9853_TRE_BA,358,HP,Color LaserJet MFP E77830,CND1N49013,2024-05-28,10.5.133.67 (Network),2024-05-28T22:39:39,5874.0,31930.0,False
282158,9853_TRE_BA,388,HP,Color LaserJet MFP E77830,CND1N48061,2024-05-28,10.5.207.44 (Network),2024-05-28T22:39:26,3577.0,13710.0,False
281279,9853_TRE_BA,385,HP,Color LaserJet MFP E77830,CND1N48060,2024-05-28,10.5.202.145 (Network),2024-05-28T22:39:31,5506.0,17330.0,False
280400,9853_TRE_BA,369,HP,Color LaserJet MFP E77830,CND1N470B0,2024-05-28,10.5.201.104 (Network),2024-05-28T22:39:28,6104.0,30521.0,False
...,...,...,...,...,...,...,...,...,...,...,...
3516,9853_TRE_BA,382,HP,LaserJet MFP E52645,BRBSN8RJMP,2022-01-01,NaN,NaN,NaN,NaN,NaN
2637,9853_TRE_BA,383,HP,LaserJet MFP E52645,BRBSN8RJMJ,2022-01-01,NaN,NaN,NaN,NaN,NaN
1758,9853_TRE_BA,629,HP,LaserJet MFP E52645,BRBSN8RJLT,2022-01-01,NaN,NaN,NaN,NaN,NaN
879,9853_TRE_BA,638,HP,LaserJet MFP E52645,BRBSN8RJLM,2022-01-01,NaN,NaN,NaN,NaN,NaN
0,9853_TRE_BA,280,HP,LaserJet MFP E52645,BRBSN8FC4P,2022-01-01,NaN,NaN,NaN,NaN,NaN

In [19]:
# Inicializa uma lista vazia para armazenar DataFrames individuais correspondentes a cada número de série
registros_impressoras = []
# Itera sobre cada linha do DataFrame 'imp'
for index, row in imp.iterrows():
    serial_number = row['SerialNumber']
    # Filtra o DataFrame 'df_merged' para obter apenas as linhas com o mesmo número de série e preenche valores nulos usando o método backward fill (bfill)
    df_parcial = df_merged[df_merged['SerialNumber'] == serial_number].bfill()
    # Adiciona o DataFrame filtrado e preenchido à lista 'impressoras'
    registros_impressoras.append(df_parcial)

# Concatena todos os DataFrames na lista 'impressoras' em um único DataFrame, ignorando os índices originais
df_filled = pd.concat(registros_impressoras, ignore_index=True)

In [20]:
df_filled

,EnterpriseName,PrinterDeviceID,BrandName,PrinterModelName,SerialNumber,RealDateCapture,AddressName,DateTimeRead,ReferenceMono,ReferenceColor,Engaged
0,9853_TRE_BA,280,HP,LaserJet MFP E52645,BRBSN8FC4P,2024-05-28,10.171.24.60 (Network),2024-05-28T22:39:32,52349.0,0.0,False
1,9853_TRE_BA,280,HP,LaserJet MFP E52645,BRBSN8FC4P,2024-05-27,10.171.24.60 (Network),2024-05-27T22:34:37,52345.0,0.0,False
2,9853_TRE_BA,280,HP,LaserJet MFP E52645,BRBSN8FC4P,2024-05-26,10.171.24.60 (Network),2024-05-26T22:29:24,52335.0,0.0,False
3,9853_TRE_BA,280,HP,LaserJet MFP E52645,BRBSN8FC4P,2024-05-25,10.171.24.60 (Network),2024-05-25T22:22:31,52335.0,0.0,False
4,9853_TRE_BA,280,HP,LaserJet MFP E52645,BRBSN8FC4P,2024-05-24,10.171.24.60 (Network),2024-05-24T22:17:48,52335.0,0.0,False
...,...,...,...,...,...,...,...,...,...,...,...
305887,9853_TRE_BA,659,HP,Laser 408dn,BRBSRC60PQ,2022-01-05,NaN,NaN,NaN,NaN,NaN
305888,9853_TRE_BA,659,HP,Laser 408dn,BRBSRC60PQ,2022-01-04,NaN,NaN,NaN,NaN,NaN
305889,9853_TRE_BA,659,HP,Laser 408dn,BRBSRC60PQ,2022-01-03,NaN,NaN,NaN,NaN,NaN
305890,9853_TRE_BA,659,HP,Laser 408dn,BRBSRC60PQ,2022-01-02,NaN,NaN,NaN,NaN,NaN
305891,9853_TRE_BA,659,HP,Laser 408dn,BRBSRC60PQ,2022-01-01,NaN,NaN,NaN,NaN,NaN

In [21]:
# Converte a coluna 'RealDateCapture' para o tipo datetime
df_filled['RealDateCapture'] = pd.to_datetime(df_filled['RealDateCapture'])
# Filtra o DataFrame para incluir apenas os registros onde 'RealDateCapture' é posterior à data de 01/01/2024
df_filled_2024 = df_filled[df_filled['RealDateCapture'] > '2024-01-01']
# Preenche os valores nulos do DataFrame filtrado com 0
df_filled_2024 = df_filled_2024.fillna(0)

In [22]:
df_filled_2024

,EnterpriseName,PrinterDeviceID,BrandName,PrinterModelName,SerialNumber,RealDateCapture,AddressName,DateTimeRead,ReferenceMono,ReferenceColor,Engaged
0,9853_TRE_BA,280,HP,LaserJet MFP E52645,BRBSN8FC4P,2024-05-28,10.171.24.60 (Network),2024-05-28T22:39:32,52349.0,0.0,False
1,9853_TRE_BA,280,HP,LaserJet MFP E52645,BRBSN8FC4P,2024-05-27,10.171.24.60 (Network),2024-05-27T22:34:37,52345.0,0.0,False
2,9853_TRE_BA,280,HP,LaserJet MFP E52645,BRBSN8FC4P,2024-05-26,10.171.24.60 (Network),2024-05-26T22:29:24,52335.0,0.0,False
3,9853_TRE_BA,280,HP,LaserJet MFP E52645,BRBSN8FC4P,2024-05-25,10.171.24.60 (Network),2024-05-25T22:22:31,52335.0,0.0,False
4,9853_TRE_BA,280,HP,LaserJet MFP E52645,BRBSN8FC4P,2024-05-24,10.171.24.60 (Network),2024-05-24T22:17:48,52335.0,0.0,False
...,...,...,...,...,...,...,...,...,...,...,...
305156,9853_TRE_BA,659,HP,Laser 408dn,BRBSRC60PQ,2024-01-06,0,0,0.0,0.0,0
305157,9853_TRE_BA,659,HP,Laser 408dn,BRBSRC60PQ,2024-01-05,0,0,0.0,0.0,0
305158,9853_TRE_BA,659,HP,Laser 408dn,BRBSRC60PQ,2024-01-04,0,0,0.0,0.0,0
305159,9853_TRE_BA,659,HP,Laser 408dn,BRBSRC60PQ,2024-01-03,0,0,0.0,0.0,0
305160,9853_TRE_BA,659,HP,Laser 408dn,BRBSRC60PQ,2024-01-02,0,0,0.0,0.0,0

In [26]:
df_filled_2024.describe()

       PrinterDeviceID      RealDateCapture  ReferenceMono  ReferenceColor
count     51504.000000                51504   51504.000000    51504.000000
mean        467.436782  2024-03-15 12:00:00   31405.199111     1053.262640
min         268.000000  2024-01-02 00:00:00       0.000000        0.000000
25%         379.750000  2024-02-07 18:00:00   11606.500000        0.000000
50%         467.500000  2024-03-15 12:00:00   30043.000000        0.000000
75%         554.250000  2024-04-21 06:00:00   45648.750000        0.000000
max         661.000000  2024-05-28 00:00:00  113349.000000    58097.000000
std         103.328426                  NaN   22425.512748     4901.156885

In [23]:
# Salvar o DataFrame resultante
df_filled_2024.to_csv('D:/projetos/simpress/testes/df_filled_2024.csv', index=False)